# .coderabbit.yaml
language: "vi-VN"
early_access: false
reviews:
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "Draft"
    patterns:
      - "**/*.ts"
      - "**/*.tsx"
      - "**/*.js"
      - "!**/node_modules/**"
      - "!**/dist/**"

chat:
  auto_reply: true
