import '@shared/styles/globals.css';

import { AuthProvider } from '@shared/providers/auth-provider';
import QueryProvider from '@shared/providers/query-provider';
import { ThemeProvider } from '@shared/providers/theme-provider';
import { ToastProvider } from '@shared/providers/toast-provider';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              {children}
              <ToastProvider />
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
