import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@shared/styles/globals.css";
import { ThemeProvider } from "@shared/providers/theme-provider";
import QueryProvider from "@shared/providers/query-provider";
import { AuthProvider } from "@shared/providers/auth-provider";
import { ToastProvider } from "@shared/providers/toast-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              {children}
              <ToastProvider />
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
