import '@shared/styles/globals.css';

import { AuthProvider } from '@shared/providers/auth-provider';
import QueryProvider from '@shared/providers/query-provider';
import { ThemeProvider } from '@shared/providers/theme-provider';
import { ToastProvider } from '@shared/providers/toast-provider';
import { WebSocketProvider } from '@shared/realtime/websocket-provider';
import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  variable: '--font-roboto',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={roboto.variable}>
      <body>
        <ThemeProvider>
          <QueryProvider>
            <AuthProvider>
              <WebSocketProvider>
                {children}
                <ToastProvider />
              </WebSocketProvider>
            </AuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
